### ISSUE TITLE
Wrong windows drive/path resolving -> Error ENOENT C:\c:\

### ISSUE THREAD

**Issue by niun** [phil294/GitLG#101] opened 2024-07-23 15:57 UTC
Type: <b>Bug</b>

- Open a workspace with a git repository directory on Windows 10
- Open Panel > OUTPUT > Extension Host
- Open different files in different editors (maybe those files need to be seen as modified by git)
- Switch between the open Editors

The Extension Host output now shows `[error]` lines on some editor switches like
```
2024-07-23 17:38:55.486 [error] Error: ENOENT: no such file or directory, realpath 'C:\c:\Users\username-redacted\path\to\workspace\some-modified-file.yaml'
```
My expectation is to not see those errors or have related settings reported that are responsible for path resolution and the resulting doubled drive letter.

Extension version: 0.1.15
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (19.63GB free)|
|Process Argv|--crash-reporter-id d6099137-1165-49da-92c2-38ccf25611fb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
refactort:31101459
pythonrstrctxt:31093869

```

</details>

**Comment by phil294** [comment] 2024-09-29 01:46
thanks for reporting, duplicate of #100

**Closed by phil294** 2024-09-29 01:46 UTC
