### ISSUE TITLE
ENOENT: no such file or directory via "Open graph view" button

### ISSUE THREAD

**Issue by Road-hog123** [phil294/GitLG#80] opened 2024-03-04 11:38 UTC
If I click the Git Log button in the status bar the extension works fine, but if I click the "Open graph view" button in the Source Control panel (as I normally do) I get `A system error occurred (ENOENT: no such file or directory, realpath 'C:\c:\Users\Nathan\Documents\Dev\Blender\blender')` and the graph view does not open. This happens with any repository, even a freshly-initialised one.

**Comment by phil294** [comment] 2024-03-04 22:53
this sounds a bit like #70. apprently not fixed yet, I'll have to test this on a windows system some day

**Comment by dimateos** [comment] 2024-04-24 08:19
I can confirm this error still pops up:

![image](https://github.com/phil294/git-log--graph/assets/26868611/8f68a79e-fc17-48d6-9c66-66cdd6d81a13)

In my case they pop constantly whenever I open any file, including simply changing the current open editor. So I guess is not related to the button but with queries/stuff happening at changing current active editor.

Maybe related to https://github.com/phil294/git-log--graph/issues/82 and why the buttons do not work in windows tho.

> (other closed issue) But I do understand both of you correct that you have not experienced any issues with the extension itself, only noticed the output errors, right?

Other than the button not working, no. So its perfectly usable, no noticeable vscode slowdowns either.

> As to why there was a C:\D:, I have no idea

I checked and the errors / button not working still happens even at C:/ with C:\c:\. Quite weird, the letter changes to upper/lower-case.

![image](https://github.com/phil294/git-log--graph/assets/26868611/c58978cf-043a-467d-8d4d-10549c3e135c)

> I'll have to test this on a windows system some day

Cool! The error call stack leads to nothing, not even the extension id... but if you want me to try something out let me know.

**Comment by Amanoki** [comment] 2024-09-24 14:27
Noticed the same error message as @ dimateos in my console today. They constantly pop up when vscode launches, files open, tabs switch, or when I was just typing in the editor.
For me it is `E:\ActualFilePathInAnyDisk` like `E:\d:\...` or `E:\F:\...`. Don't know why E: but E: is where my vscode is installed.

**Comment by phil294** [comment] 2024-10-01 11:20
duplicate of #100

**Closed by phil294** 2024-10-01 11:20 UTC

**Comment by phil294** [comment] 2024-10-01 12:08
fixed
